#!/bin/bash
function help() {
  echo "Usage:"
  echo "  $0 [-o|--ORG <ORG>]"
  echo
  echo "For a better experience set these alias:"
  echo "  set alias pwd to:  !gh config get current-org"
  echo "  set alias cd to:   !gh config set current-org "$1" 2>/dev/null"
  exit 1
}

POSITIONAL_ARGS=()
while [[ $# -gt 0 ]]; do
  case $1 in
  -o | --ORG)
    ORG=$2
    shift # past argument
    shift # past value
    ;;

  -* | --*)
    help
    ;;
  *)
    POSITIONAL_ARGS+=("$1") # save positional arg
    shift # past argument
    ;;
  esac
done

if [ -z "$ORG" ]; then
  ORG=$(gh pwd) || help
fi
QUERY='query getInfo($organization: String!) {
  organization(login: $organization) {
    teams(first: 100) {
      totalCount
      edges {
        node {
          name
          members(first: 100) {
            totalCount
            edges {
              memberAccessUrl
              node {
                name
                url
                email
                login               
              }
            }
          }
          url
        }
      }
    }
  }
}'

TEAMS=$(gh api graphql -F organization="$ORG" -f query="$QUERY")

echo $TEAMS
